== Persistent Memory

The command module contains a FRAM IC used for persistent storage of mission configuration details. This memory is accessed as part of the command module power-up process and determines the subsequent behavior.

The format of that stored configuration is given in the following table.

.Stored mission configuration format
[cols="1,3,1"]
|===
|Bytes |Description |Type

| 0-1
| Mission ID
| `uint16`

| 2
| Flight status: +
0 = lab +
1 = launch (waiting for lift-off) +
2 = in-flight +
3 = landed
| `uint8`

| 3
| Transmit period during flight (in seconds)
| `uint8`

| 4
| Trigger height (in meters)
| `uint8`

| 5-6
| Launch height (in meters)
| `int16`

| 10-1000
| Pod manifest
| see below
|===

Launch height::
__Launch height__ is the altitude (in meters) of the command module while waiting to be launched. It is measured by the command module upon power-up if the flight status is `launch` **and** no motion detected. It waits for a good GPS lock (minimum of 4 satellites used) before saving this value. The default value is -1000, indicating that no valid altitude has been measured yet.

Trigger height::
__Trigger height__ is the increase in altitude (in meters) above __launch height__ that causes the command module to switch its flight status from `launch` to `in-flight`.

=== Pod manifest, condensed format

The pod manifest is a description of the individual experiment pod's and the data that they will be transmitting. This takes two forms. The primary version is based on nested Python lists and dictionaries. This verbose format is used in the Mission Control server and the underlying MongoDB database. The constraints of the microcontroller necessitate a more compact (and less human-friendly) format containing a subset of the information in the primary format.

